version: "3.9"
volumes:


services:
  nginx:
    name:
    build: requirements/nginx
    ports:
      - "443:443"
    newtworks:
      - ?
  mariadb:
    name:
    build: ./requirements/mariadb
    newtworks:
      - ?
  wordpress:
    build: ./requirements/wordpress
    newtworks:
      - ?
    name: