version: '3.8'

# volumes:
#   mariadb_volume: (db):
#     driver:
#     driver_opts:
#       type:
#       o:
#       device:
#   wordpress_volume: (www):
#     driver:
#     driver_opts:
#       type:
#       o:
#       device: /home/login/data

services:
  mariadb:
    container_name: mariadb
    image: mariadb
#    volumes:
#      - db_data:/var/lib/mysql
#      - /data/mysql:/var/lib/mysql
    env_file:
      - .env
    restart: always
#  wordpress:
#    container_name: wordpress
#    image: wordpress
#    volumes:
#      - html_data:/var/www/html
#      - /data/html:/var/www/html
#    depends_on:
#      - mysql
#    environment:
#      - .env
#    ports:
#      3306
#    restart: always
  nginx:
    container_name: nginx
    image: nginx
     #volumes:
       # - nginx-data:/etc/nginx/conf.d
      # - ./nginx/conf/my_nginx.conf:/etc/nginx/conf.d/default.conf   //video!
       # - nginx:/etc/nginx/conf.d
       #- /data/html:/var/www/html
       # - html-data:/var/www/html
  #   depends_on:
  #     - wordpress
    ports:
      - 433:433
    restart: always

  # volumes:
  #   db-data:
  #   html-data:
  #   nginx-data:
