FROM debian:buster

RUN apt-get update -y
# This is a Fast CGI process manager which enables caching
RUN apt-get install php7.2-cli php7.2-fpm php7.2-mysql php7.2-json php7.2-opcache php7.2-mbstring php7.2-xml php7.2-gd php7.2-curl
